///
/// @Generated by Mockolo
///



import Foundation
@testable import AISmartExpenseAnalyzer


class AddExpenseUseCaseProtocolMock: AddExpenseUseCaseProtocol {
    init() { }


    private(set) var executeCallCount = 0
    var executeHandler: ((Decimal, String, Date) async throws -> Expense)?
    func execute(amount: Decimal, description: String, date: Date) async throws -> Expense {
        executeCallCount += 1
        if let executeHandler = executeHandler {
            return try await executeHandler(amount, description, date)
        }
        fatalError("executeHandler returns can't have a default value thus its handler must be set")
    }
}



