///
/// @Generated by Mockolo
///



import Foundation
@testable import AISmartExpenseAnalyzer

class AIProviderProtocolMock: AIProviderProtocol {
    init() { }
    init(providerName: String = "") {
        self.providerName = providerName
    }



    var providerName: String = ""

    private(set) var categorizeCallCount = 0
    var categorizeHandler: ((String, Decimal) async throws -> AIDecision)?
    func categorize(description: String, amount: Decimal) async throws -> AIDecision {
        categorizeCallCount += 1
        if let categorizeHandler = categorizeHandler {
            return try await categorizeHandler(description, amount)
        }
        fatalError("categorizeHandler returns can't have a default value thus its handler must be set")
    }
}



