///
/// @Generated by Mockolo
///



import Foundation
@testable import AISmartExpenseAnalyzer


class CategorizeExpenseUseCaseProtocolMock: CategorizeExpenseUseCaseProtocol {
    init() { }


    private(set) var executeCallCount = 0
    var executeHandler: ((Expense) async throws -> Expense)?
    func execute(expense: Expense) async throws -> Expense {
        executeCallCount += 1
        if let executeHandler = executeHandler {
            return try await executeHandler(expense)
        }
        fatalError("executeHandler returns can't have a default value thus its handler must be set")
    }
}



