///
/// @Generated by Mockolo
///



import Foundation
@testable import AISmartExpenseAnalyzer

class DeleteExpenseUseCaseProtocolMock: DeleteExpenseUseCaseProtocol {
    init() { }


    private(set) var executeCallCount = 0
    var executeHandler: ((UUID) async throws -> ())?
    func execute(id: UUID) async throws {
        executeCallCount += 1
        if let executeHandler = executeHandler {
            try await executeHandler(id)
        }
        
    }
}



