///
/// @Generated by Mockolo
///



import Foundation
@testable import AISmartExpenseAnalyzer


class ExpenseRepositoryProtocolMock: ExpenseRepositoryProtocol {
    init() { }


    private(set) var saveCallCount = 0
    var saveHandler: ((Expense) async throws -> ())?
    func save(_ expense: Expense) async throws {
        saveCallCount += 1
        if let saveHandler = saveHandler {
            try await saveHandler(expense)
        }
        
    }

    private(set) var fetchAllCallCount = 0
    var fetchAllHandler: (() async throws -> [Expense])?
    func fetchAll() async throws -> [Expense] {
        fetchAllCallCount += 1
        if let fetchAllHandler = fetchAllHandler {
            return try await fetchAllHandler()
        }
        return [Expense]()
    }

    private(set) var fetchCallCount = 0
    var fetchHandler: ((ExpenseFilter) async throws -> [Expense])?
    func fetch(filter: ExpenseFilter) async throws -> [Expense] {
        fetchCallCount += 1
        if let fetchHandler = fetchHandler {
            return try await fetchHandler(filter)
        }
        return [Expense]()
    }

    private(set) var fetchIdCallCount = 0
    var fetchIdHandler: ((UUID) async throws -> Expense?)?
    func fetch(id: UUID) async throws -> Expense? {
        fetchIdCallCount += 1
        if let fetchIdHandler = fetchIdHandler {
            return try await fetchIdHandler(id)
        }
        return nil
    }

    private(set) var updateCallCount = 0
    var updateHandler: ((Expense) async throws -> ())?
    func update(_ expense: Expense) async throws {
        updateCallCount += 1
        if let updateHandler = updateHandler {
            try await updateHandler(expense)
        }
        
    }

    private(set) var deleteCallCount = 0
    var deleteHandler: ((UUID) async throws -> ())?
    func delete(id: UUID) async throws {
        deleteCallCount += 1
        if let deleteHandler = deleteHandler {
            try await deleteHandler(id)
        }
        
    }

    private(set) var fetchPendingCategorizationCallCount = 0
    var fetchPendingCategorizationHandler: (() async throws -> [Expense])?
    func fetchPendingCategorization() async throws -> [Expense] {
        fetchPendingCategorizationCallCount += 1
        if let fetchPendingCategorizationHandler = fetchPendingCategorizationHandler {
            return try await fetchPendingCategorizationHandler()
        }
        return [Expense]()
    }
}



