///
/// @Generated by Mockolo
///



import Foundation
@testable import AISmartExpenseAnalyzer

class GenerateInsightsUseCaseProtocolMock: GenerateInsightsUseCaseProtocol {
    init() { }


    private(set) var executeCallCount = 0
    var executeHandler: (([Expense]) async throws -> [Insight])?
    func execute(for expenses: [Expense]) async throws -> [Insight] {
        executeCallCount += 1
        if let executeHandler = executeHandler {
            return try await executeHandler(expenses)
        }
        return [Insight]()
    }
}



