///
/// @Generated by Mockolo
///



import Foundation
@testable import AISmartExpenseAnalyzer


class GetExpensesUseCaseProtocolMock: GetExpensesUseCaseProtocol {
    init() { }


    private(set) var executeCallCount = 0
    var executeHandler: ((ExpenseFilter) async throws -> [Expense])?
    func execute(filter: ExpenseFilter) async throws -> [Expense] {
        executeCallCount += 1
        if let executeHandler = executeHandler {
            return try await executeHandler(filter)
        }
        return [Expense]()
    }
}



